### PR TITLE
add scenario tests framework

### PR DESCRIPTION
**Pull request by guangyee**
Utilizing pytest and jinja2 templating to simplify the process in
developing scenario tests. Test developers can easily create request
templates and load them into JSON request objects by provide only the
required fields. The templates, along with their corresponding fixtures
are designed to be reusable. With templating, the goal is to reduce the
complexity of having to handcraft the JSON request in every test.

### CODE REVIEW

**Comment by mbelur** [comment]
Looks Good! one suggestion is to move the common code like utils, fixture and templates so it can also be consumed by the API tests.

**Comment by guangyee** [comment]
> Looks Good! one suggestion is to move the common code like utils, fixture and templates so it can also be consumed by the API tests.

Good suggestion! We probably will need to re-org the directories to have a top level parent directory `harvester-test`. i.e.

tests/harvester-tests
tests/harvester-tests/fixtures
tests/harvester-tests/templates
tests/harvester-tests/scenarios
tests/harvester-tests/apis

I can do that in a follow-on PR.

**Review by mbelur — APPROVED** [review]
LGTM!

**Review by guangbochen — APPROVED** [review]
LGTM

**Pull request merged**
