### PR TITLE
update e2e testing scenarios

### PR DESCRIPTION
**Pull request by lanfon72**
## Changes
- Implement `ClusterNetworkManager` in apiclient for relevant API calls
- Update fixture `enable_vlan` to create cluster network when the Harvester version over `v1.0.3`

### need to update terraform test cases and resources
- [ ] harvester_e2e_tests/integration/test_terraform.py::test_create_network_using_terraform::setup  
- [ ] harvester_e2e_tests/integration/test_terraform.py::test_create_volume_using_terraform::setup   
- [ ] harvester_e2e_tests/scenarios/test_vm_networking.py::test_create_vm_using_terraform::setup   
### randomly failed, need to figure a better way to test
- [ ] harvester_e2e_tests/scenarios/test_create_vm.py::test_create_vm_on_available_cpu_node  
- [ ] harvester_e2e_tests/scenarios/test_create_vm.py::test_update_vm_on_available_cpu_node  
### `affinity` will be added, but while update VM, affinity will be removed automatically, need to check whether it is API issue or not
- [ ] harvester_e2e_tests/scenarios/test_vm_networking.py::TestVMNetworking::test_remove_vlan_network_from_vm 
- [ ] harvester_e2e_tests/scenarios/test_vm_networking.py::test_update_vm_vlan_network_to_management

### CODE REVIEW

**Comment by lanfon72** [comment]
Tested on `harvester-runtests#80`

**Review by khushboo-rancher — CHANGES_REQUESTED** [review]
Can you revert the config.yml changes?

**Comment by khushboo-rancher** [comment]
Instead of modifying the existing fixtures, let's create a new directories and have new fixtures there. Because in future it will become tough and tedious work to remove the old code.

**Comment by lanfon72** [comment]
> Instead of modifying the existing fixtures, let's create a new directories and have new fixtures there. Because in future it will become tough and tedious work to remove the old code.

Extending old fixtures is the simplest way to fix multiple test cases, otherwise we will need to update all test cases.
(it would almost equals to re-write those test cases if use new fixtures)

**Review by noahgildersleeve — APPROVED** [review]
LGTM. Tested apis/test_networks.py and it passed and properly parsed my v1.1.1 cluster and correctly set VM network and handled cluster netowrks.

**Comment by khushboo-rancher** [comment]
@lanfon72 Can you squash all the commits to 1 commit and then we can merge this.

**Comment by lanfon72** [comment]
> @lanfon72 Can you squash all the commits to 1 commit and then we can merge this.

It requires to update in repository settings.
image

**Pull request merged**
