### PR TITLE
Enhance apis test images

### PR DESCRIPTION
**Pull request by albinsun**
Propose some enhancement during verify harvester#3889 [[ENHANCEMENT] Harvester Single Node Cluster](https://github.com/harvester/harvester/issues/3889)

## Changes
1. Put test generated cache & report to .gitignore, includes:
   1. .tox
   1. test_result.json
   1. .report.json

1. Enhance TC error due to delete an image which is Initialized but still **Importing** 
   * Test Suite: `apis/test_images.py::TestImages`
   * Problem
     1. `api_client.images.get` reply 200 as long as the image status is `Initialized`. But it's possible that Longhorn still `Importing` it (`Initialized` but not `Imported` yet)
        <details>
          <summary>Imported v.s. Importing status in images.get response body</summary>
        
          importing_and_imported
        </details>
     1. Due to this, `test_get` is passed since it consider upload (`test_create`) was succeeded, thus immediately trigger `test_delete` on the image which Longhorn is still importing.
     1. This causes image record is deleted on Harvester but still existed on Longhorn, and causes successive TC `test_create_with_reuse_display_name` fail (504) due to it use the same image name `unique_name` which is still processing).
        <details>
          <summary>Fail example on harvester-runtests#277</summary>

          test_images-harvester-runtests#277
        </details>
        
        <details>
          <summary>Image is deleted on Harvester but Longhorn is still processing.</summary>
        
          Screenshot_20230531_184652
          Screenshot_20230531_152020
        </details>

   * Solution
     * Confirm image DO `Imported` after `api_client.images.create_by_file`
     * Tested on `harvester-runtests#278`
     test_images-harvester-runtests#278

### CODE REVIEW

**Review by khushboo-rancher — CHANGES_REQUESTED** [review]
I'm fine with a temporary solution to avoid the failures. Just two things.
1. Could you please change the `image_do_created` name to something like `verify_image_created`.
2. Add a note that this is a temporary fix and being done to fix the #bugid where ever we are introducing `image_do_created` check.

**Comment by albinsun** [comment]
> I'm fine with a temporary solution to avoid the failures. Just two things.
> 
> 1. Could you please change the `image_do_created` name to something like `verify_image_created`.
> 2. Add a note that this is a temporary fix and being done to fix the #bugid where ever we are introducing `image_do_created` check.

Refactored and tested on harvester-runtests#288
image

**Comment by lanfon72** [comment]
I have the opposing opinion.

From the perspective of automation,
- We want discover bugs, not chasing **PASS rate**
- An automation test case reflect to a manual test case
- Those failures are **real** bug, not automation's bug.

From the perspective of test case
- A existing test case having specific scenario (from manual test case)
- We implement the automation test case to fit the scenario, **not** change the scenario to fit test case.


So, do we really need to add the change for those test cases?

image

When you look into the daily test failures, there have **8** failures, to exclude `scenarios`, others are similar and showing it is about **recreate images with same name**, and those test cases are **PASS** in the beginning of `v1.2.0`.

So, are we going to update the scenario? In my opinion, we shouldn't.  this failures reflect that we have a bug about **recreate images with same name**, and we should aware this, not change the automation's steps to let it **PASS**. (otherwise, the test case would be changed to another scenario)


> But how about `create_invalid_url`?  the scenario is not about **recreate images with same name**.

Yes, this is automation's bug, It failed because the side effect of `unique_name`, we reuse the name to create **invalid image**, so we should fix the side effect to let the test case to not affected by the (discovered) bug.

**Comment by albinsun** [comment]
FYI, developer already puts the related issue to v1.2.0 scope.
https://github.com/harvester/harvester/issues/4027
We can also watching it first

**Comment by khushboo-rancher** [comment]
Yeah, the [issue](https://github.com/harvester/harvester/issues/4027) is now scoped for 1.2.0. So, we'll wait for the fix.

@lanfon72 My point was that In general, if any low severity bug is impacting multiple test cases and not going to get fixed soon, we should consider to have a temporary fix so that we'll not miss running important test cases.

**Pull request closed without merging**
