### PR TITLE
Cypress v10 upgrade

### PR DESCRIPTION
**Pull request by noahgildersleeve**

### CODE REVIEW

**Review by TachunLin — COMMENTED** [review]
Verified can install cypress 10.2 and related package correctly
Can launch dashboard runner and load all test spec suites.
The package and cypress config file working as expected. 

But the regression test the existing test case found some of the test case got failure. 
According to the error message, suggest we should let the creator to take a look at their test spec file can running correctly under Cypress 10.2 environment.  

- [x] All VM settings tests: **PASS** 
  image
  image

- [x] All Network settings tests: **PASS**
image

- [ ] `Configure backup target` failed in settings.ts
image

- [x] All login test in dashboard.spec: **PASS** 
image
image

- [ ] All tests in hosts.spec got failure
image
image

- [ ] Most of the image test got failed since the first test block the rest of the cases
```
Error running data-source command: Get \"http://downloadcontent.opensuse.org/repositories/Cloud:/Images:/Leap_15.3/images/openSUSE-Leap-15.3.x86_64-NoCloud.qcow2\": context deadline exceeded."
```
image

* Most of the VM test case would failed because of the blocker of image test

**Comment by noahgildersleeve** [comment]
@TachunLin I tested this as well and saw those, however they seemed to also fail with Cypress v9.x as well. This was from two runs of `npx cypress run` with the old version of cypress and with `v10.2.0`. I agree that we need to fix those tests, but I don't think that the failures are related to the version upgrade.
Screenshot_20220623_175106
Screenshot_20220623_170343

**Comment by noahgildersleeve** [comment]
I just verified with v9.x and the hosts tests still fail. It seems like an issue with the selectors.
Screenshot_20220624_092511
The image tests are failing due to timeouts. We can fix that, but it's out of scope for this PR. I will take a look at fixing these after we get this merged in.

**Comment by TachunLin** [comment]
@noahgildersleeve, 
I also find these test would also failed at Cypress 9.3.1 too. 
Since we have other Cypress PR to enhance and fix the image, volume, vm test specs.
Agree with you we can merge the pull request first and notify them to also check the running status of test on Cypress 10.2.

**Review by TachunLin — APPROVED** [review]
The cypress config and package change can work as expected on Cypress 10.2
Let's merge the PR first and regression the existing test specs on the new version

**Review by irishgordo — APPROVED** [review]
Screenshot from 2022-06-24 10-08-58
Screenshot from 2022-06-24 09-42-38
Screenshot from 2022-06-24 09-40-53

Seeing the similar results that have already been mentioned surrounding:
```
  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  cloud-config-templates.spec.ts           00:35        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  ssh-keys.spec.ts                         00:21        1        1        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  0_FirstTimeLogin.spec.ts                 00:01        4        -        -        4        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  1_login.spec.ts                          00:12        3        3        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  hosts.spec.ts                            02:44        3        -        3        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  support.spec.ts                          00:56        4        4        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  namespaces.spec.ts                         0ms        -        -        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  images.spec.ts                           03:12        5        1        4        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  network.spec.ts                          00:39        3        3        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  settings.spec.ts                         01:55        6        5        1        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  advanced.spec.ts                         03:20        3        -        3        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  cpu-overcommit.spec.ts                   00:28        1        -        1        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  network.spec.ts                            0ms        -        -        1        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  virtual-machine.spec.ts                    0ms        -        -        1        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  volumes.spec.ts                            0ms        -        -        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  7 of 15 failed (47%)                     14:26       35       19       14        4        -  
```

This was tested on the commit #68410a46 via the cypress-v10-upgrade branch.
On Harvester Master ISO at commit #c2960206
Running as VM via QEMU/KVM managed by VirtManager with 8 CPU & 16GiB RAM

**Pull request merged**
