### PR TITLE
Clean up legacy code

### PR DESCRIPTION
**Pull request by khushboo-rancher**
1.  Deleted the test_user.py as it is not applicable now.
2. Removed the test `test_create_vm_do_not_start` as we have implemented as per new framework.
3. Deleted Rancher integration file, we have implemented as per new framework. https://github.com/harvester/tests/issues/784 is required to run the RKE1 tests.
4.  Removed the test `test_vm_network_with_bogus_vlan` as we have implemented as per new framework.

Signed-off-by: Khushboo [fnu.khushboo@suse.com](mailto:fnu.khushboo@suse.com)

### CODE REVIEW

**Comment by lanfon72** [comment]
## TODO items in `scenarios/`
- `test_rancher_integration.py`
    - [ ] add `test_import_harvester_into_rancher`
    - [ ] add `test_add_project_owner_user`
    - [x] add `test_create_rke1_cluster`  covered in `integration/test_rancher_integration.py::TestRKE`
    - [x] add `test_create_rke2_cluster`  covered in `integration/test_rancher_integration.py::TestRKE`

 - `test_vm_negatives.py`
    - [ ] add `test_host_shutdown`
    - [ ] add `test_delete_vm_while_host_shutdown`
    - [ ] add `test_vm_after_host_reboot`

- `test_vm_networking`
    - [ ] add `test_ssh_to_vm`
    - [ ] add `test_vlan_ip_pingable_after_reboot`
    - [ ] add `test_vlan_network_to_vm`
    - [ ] add `test_remove_vlan_network_from_vm`
    - [ ] add `test_two_vms_on_same_vlan`
    - [ ] add `test_update_vm_management_network_to_vlan`
    - [ ] add `test_update_vm_vlan_network_to_management`
    - [ ] add `test_vm_network_with_bogus_vlan`
    - [ ] add `test_create_update_vm_user_data`
    - [ ] add `test_create_vm_using_terraform`
    - [ ] add `test_backup_restore_new_vm`
    - [ ] add `test_backup_restore_existing_vm`
    - [ ] add `test_chained_del_middle_backup`
    - [ ] add `test_chained_del_first_backup`
    - [ ] add `test_chained_del_last_backup`
    - [ ] add `test_restore_chained_backups`
    - [ ] add `test_backup_restore_new_vm_nfs`
    - [ ] add `test_backup_restore_existing_vm_nfs`
    - [ ] add `test_chained_del_middle_backup_nfs`
    - [ ] add `test_chained_del_first_backup_nfs`
    - [ ] add `test_chained_del_last_backup_nfs`
    - [ ] add `test_restore_chained_backups_nfs`

- `test_create_vm`
    - [x] add `test_create_single_vm`  covered in `integration/test_vm_functions.py::test_minimal_vm`
    - [ ] add `test_create_windows_vm`  Need more time to implement: #804
    - [ ] ~~add `test_create_multiple_vms`~~  Not applicable, there is no API endpoint to create multiple VM at once
    - [x] add `test_create_vm_overcommit_cpu_and_memory_failed`    covered in `integration/test_vm_functions.py::test_create_vm_no_available_resources`
    - [x] add `test_create_vm_overcommit_cpu_failed`    covered in `integration/test_vm_functions.py::test_create_vm_no_available_resources`
    - [x] add `test_create_vm_overcommit_memory_failed`    covered in `integration/test_vm_functions.py::test_create_vm_no_available_resources`
    - [x] add `test_create_vm_do_not_start`  covered in `integration/test_vm_functions.py::test_create_stopped_vm`
    - [ ] add `test_create_update_vm_enable_usb`
    - [ ] add `test_create_update_vm_enable_user_data`
    - [x] add `test_create_update_vm_machine_type`  covered in `integration/test_vm_functions.py::test_update_vm_machine_type`
    - [ ] add `test_create_vm_on_available_cpu_node`
    - [ ] add `test_update_vm_on_available_cpu_node`
    - [ ] add `test_create_vm_on_available_memory_node`
    - [ ] add `test_update_vm_on_available_memory_node`
    - [ ] add `test_create_vm_on_available_cpu_and_memory_nodes`
    - [x] add `test_host_maintenance_mode`  covered in `integration/test_hosts.py::test_maintenance_mode_trigger_vm_migrate`

- `test_vm_actions`
    - [x] add `test_restart_vm`  covered in `integration/test_vm_functions.py::TestVMOperations`
    - [x] add `test_stop_vm`  covered in `integration/test_vm_functions.py::TestVMOperations`
    - [x] add `test_start_vm`  covered in `integration/test_vm_functions.py::TestVMOperations`
    - [x] add `test_pause_vm`  covered in `integration/test_vm_functions.py::TestVMOperations`
    - [x] add `test_unpause_vm`  covered in `integration/test_vm_functions.py::TestVMOperations`
    - [ ] add `test_update_vm_cpu`
    - [x] add `test_create_vm_with_external_volume`   covered in `integration/test_vm_functions.py::TestVMWithVolumes`
    - [ ] add `test_delete_volume_in_use`
    - [ ] add `test_delete_vm_then_volumes`
    - [ ] add `test_backup_single_vm_s3`
    - [ ] add `test_backup_single_vm_nfs`
    - [ ] add `test_backup_restore_migrated_vm_s3`
    - [ ] add `test_backup_restore_migrated_vm_nfs`
    - [ ] add `test_update_backup_yaml_nfs`
    - [ ] add `test_update_backup_yaml_s3`
    - [ ] add `test_restore_backup_vm_on`

**Comment by lanfon72** [comment]
## TODO items in `integration/`
- `test_volumes.py`
- `test_terraform.py`

## TODO items in `fixtures/`
- `api_endpoints.py`
- `api_version.py`
- `backuptarget.py`
- `image.py`
- `keypair.py`
- `network.py`
- `session.py`
- `support_bundle.py`
- `user.py`
- `vm.py`
- `vm_template.py`
- `volume.py`

## Others
- `templates/`
    - All `*.json.j2` been covered in `apiclient`
    - All `*.tf.j2` need to rework which related to `integration/test_terraform.py`
- `utils.py` could be removed when all TODO items above been reworked.
- `conftest.py` **deprecated markers need to be removed.

**Comment by lanfon72** [comment]
All legacy code been removed.
Tested on `harvester-runtests#452`

**Review by albinsun — APPROVED** [review]
LGTM

**Pull request merged**
