### PR TITLE
Add cretea multiple vm node scheduler test case

### PR DESCRIPTION
**Pull request by WuJun2016**
# links
- https://github.com/harvester/harvester/issues/1824

### CODE REVIEW

**Review by noahgildersleeve — APPROVED** [review]
LGTM

**Comment by noahgildersleeve** [comment]
Conflicts need to be resolved.

**Review by TachunLin — APPROVED** [review]
LGTM.

**Review by noahgildersleeve — APPROVED** [review]
LGTM

**Comment by WuJun2016** [comment]
@noahgildersleeve   Done.   PTAL. thanks

**Review by noahgildersleeve — APPROVED** [review]
LGTM

**Pull request merged**
