### PR TITLE
doc: Introduce Rancher2 Terraform Integration Test Doc

### PR DESCRIPTION
**Pull request by irishgordo**
* provides baseline integration test documentation of manual test for rancher2 terraform provider w/ Rancher v2.7.X, Harvester, and the terraform provider plugin rancher2

Resolves: doc/terraform-rancher2-integration-manual-testing

Tested Locally:
Screenshot from 2023-05-01 12-30-56

### CODE REVIEW

**Review by khushboo-rancher — CHANGES_REQUESTED** [review]
LGTM, just move the file from incoming to Harvester Rancher2 Terraform integration.

**Comment by irishgordo** [comment]
@khushboo-rancher  sounds good :smile:  :+1: 

I have removed them from `_incoming`, provided them their own section (so we can expand on in the future), and updated the pr - validating locally x-ref screengrabs:

Screenshot from 2023-05-01 16-38-29
Screenshot from 2023-05-01 16-39-30

**Comment by khushboo-rancher** [comment]
Thanks @irishgordo, 
Just one doubt why the file name is `1009_terraform_rancher2_provider_testing.md`?

**Comment by irishgordo** [comment]
Updated :smile:

**Review by khushboo-rancher — APPROVED** [review]

**Pull request merged**
