### PR TITLE
* [CY] decoupling env variables and documents

### PR DESCRIPTION
**Pull request by lanfon72**
Changes:
- Move `env` variables from `cypress.json` into `cypress.env.json.example` ( `cypress.env.json` should be ignored by git)
- Move cypress' ignores from `.gitignore` into `cypress/.gitignore`
- Move cypress' document from `README.md` into `cypress/README.md`
- Update **Contribution** info into `cypress/README.md`

Review the changes: https://github.com/lanfon72/tests/tree/dev/cypress

### CODE REVIEW

**Review by WuJun2016 — APPROVED** [review]
LGTM

**Review by TachunLin — APPROVED** [review]
LGTM. 

Follow the README.md to setup Cypress. 
Can use cypress.env.json to run Harvester tests   

The only difference is by using `npm ci` get the following error. 
Thus I use `npm install` instead, the rest of the instruction work weel 

```
davidtclin@localhost:~/Documents/Harvester/workspace/Review_PR/tests/cypress> npm ci
npm ERR! cipm can only install packages with an existing package-lock.json or npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or later to generate it, then try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/davidtclin/.npm/_logs/2022-05-18T03_50_15_264Z-debug.log
```

**Comment by lanfon72** [comment]
@TachunLin `package-lock.json` should exists in `tests/cypress`, could you check node version via `node --version` and npm versioni via `npm version` ?

**Comment by lanfon72** [comment]
[Here](https://stackoverflow.com/a/44210813) is the reason to include `package-lock.json`

**Comment by TachunLin** [comment]
My node version using `v14.17.5` and the npm version is `6.14.14`

**Comment by lanfon72** [comment]
`npm ci` should works now, please check again and merge the PR if it works.

**Comment by lanfon72** [comment]
yeah you did `npm install` before, you can remove `node_modules/` and do `npm ci` again

**Pull request merged**
