### PR TITLE
updated filenames to remove hashes so that the GH pages worked properly

### PR DESCRIPTION
**Pull request by noahgildersleeve**

### CODE REVIEW

**Review by lanfon72 — APPROVED** [review]
LGTM

**Review by TachunLin — CHANGES_REQUESTED** [review]
Checked locally for github page preview

Found file name start with 1634 and 1655 share the same title `Verify network data template` 
and 1660 and 1661 share the same title `Verify that vm-force-reset-policy works` 

Which make GH page show up identical test cases

image

image

**Review by guangyee — APPROVED** [review]
lgtm

**Comment by noahgildersleeve** [comment]
Closing to PR from separate Repo.

**Pull request closed without merging**
