### PR TITLE
feat: Introduce Dockerized Backend Tests

### PR DESCRIPTION
**Pull request by irishgordo**
* dockerizing backend tests for better portability for CI and beyond
* introduction of Makefile hooks for ease-of-use

Resolves: feat/dockerize-backend-testing

### CODE REVIEW

**Review by lanfon72 — APPROVED** [review]
LGTM, It looks we can also fix CodeFactor's errors to reduce the size of image.

**Comment by irishgordo** [comment]
I'm trying out some codefactor suggestions right now :smile:  - will push some changes after I validate the image integrity

**Review by slickwarren — COMMENTED** [review]
lgtm

**Comment by irishgordo** [comment]
I have the changes stashed on my current local branch, since I simply don't on my local machine have the horsepower to run a Jenkins pipeline, Harvester, and Rancher all airgapped, I pushed it to:
https://github.com/irishgordo/tests/commit/127eb0990ebcfc411e63a118f548bef72aee5ef4

Which is the "temporary" feature branch used for a Jenkins instance's pipeline - in order to validate that there are not any issues present-  cleaning the apt lists & passing the `--no-install-recommends` prior to snagging some packages.

If the pipeline does not generate any anomalous errors, I will go ahead and `git stash pop` and then force commit amend up to this feature branch :smile:   -> then that should eliminate the CodeFactor issues

**Review by khushboo-rancher — APPROVED** [review]

**Pull request merged**
