### PR TITLE
[CY] verify UI url

### PR DESCRIPTION
**Pull request by WuJun2016**
1. add Verify the Harvester UI URL:  https://harvester.github.io/tests/manual/ui/verify-url/

### CODE REVIEW

**Comment by TachunLin** [comment]
The test suite pass the first test but failed at the second
  image



The second test case `Verify the Harvester icon on the left top corner` failed at  `[testcases/dashboard/nav.spec.ts:21:8]`
  image
  
  ```
  The command was expected to run against origin https://192.168.122.239 
  but the application is at origin about://blank.
  ```

After removing the `experimentalSessionAndOrigin: true,` in `cypress.config.ts` 
The second case can execute correctly in sequence. 
image

**Review by TachunLin — CHANGES_REQUESTED** [review]
By removing the `experimentalSessionAndOrigin: true`, in `cypress.config.ts`. 
The test suite can run correctly. 
Not sure whether removing would impact any existing test cases.

**Comment by WuJun2016** [comment]
@TachunLin  It's been fixed. I tested it several times and it works.  PTAL again, thanks

**Review by TachunLin — APPROVED** [review]
LGTM. Tested several time on v1.1.1-rc2 without error. 

image

image

**Pull request merged**
