### PR TITLE
regression: Authentication

### PR DESCRIPTION
**Pull request by lanfon72**
Chagnes:
1. Remove old `first login` test case
2. Implement 4 test cases of first time login
3. Add several methods for `Login.po`
4. To fix hook bug[^1], create `dashboard/0_FirstTimeLogin.spec.ts` and moved `login.spec.ts` to `dashboard/1_login.spec.ts`
5. Implement `invalid login` and `logout from valid login`
6. Add `nav` and `header` for `PagePo`

[^1]: `after` hook will have collision if there have multiple `describe` function in a file, the reference: https://stackoverflow.com/a/56193026

### CODE REVIEW

**Comment by lanfon72** [comment]
Numbering test files is a easy way to order the execution :thinking:

**Comment by WuJun2016** [comment]
> Numbering test files is a easy way to order the execution 🤔

Yes, prefixing with numbers is one way to do it, but as test cases are added, if the order of some test cases needs to be inserted in the middle, then you need to change all the file names.

**Comment by lanfon72** [comment]
I think we probably don't need to order all test cases (in the folder), but to consider those test cases combination, we would need a meeting to discuss it after test cases grown.

**Comment by lanfon72** [comment]
Test cases of **Authentication** will be fulfilled in this PR. (except Rancher related)

**Review by TachunLin — COMMENTED** [review]
When we click the running integration tests 
image

The test suite would failed at the the `invalid login` test under the login page for harvester description group
Which blocks the remaining test in the suite
image

While we run the first time login page individually follow by the login page for harvester 
Both cases are running correctly
image

image

**Comment by lanfon72** [comment]
> The test suite would failed at the the invalid login test under the login page for harvester description group
Which blocks the remaining test in the suite

Fixed the racing condition.

**Comment by irishgordo** [comment]
I had this run against my local bare-metal version of Harvester and it looks good :smile:  :+1: 
```
suse-workstation-team-harvester➜  cypress : 7d0b4570 ✘ :✖ ᐅ  npx cypress run testcases/dashboard/0_FirstTimeLogin.spec.ts testcases/dashboard/1_login.spec.ts 

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        9.3.1                                                                          │
  │ Browser:        Electron 94 (headless)                                                         │
  │ Node Version:   v16.14.2 (/home/mike/.nvm/versions/node/v16.14.2/bin/node)                     │
  │ Specs:          11 found (dashboard/0_FirstTimeLogin.spec.ts, dashboard/1_login.spec.ts, dashb │
  │                 oard/hosts.spec.ts, dashboard/support.spec.ts, settings/settings.spec.ts, name │
  │                 spaces/namespaces.spec.ts, volume/volumes.spec.ts, image/images.spec.ts, netwo │
  │                 rks/network.spec.ts, VM...)                                                    │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  dashboard/0_FirstTimeLogin.spec.ts                                             (1 of 11)


  First Time Login Page
    Check Options
      - is required to accept term
      - is optional to accept collection of anonymous statstics
    Set Password
      - Password inconsistant
      - Password consistant


  0 passing (687ms)
  4 pending


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        4                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      4                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     0 seconds                                                                        │
  │ Spec Ran:     dashboard/0_FirstTimeLogin.spec.ts                                               │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Video)

  -  Started processing:  Compressing to 32 CRF                                                     
  -  Finished processing: /home/mike/Projects/tests/cypress/cypress/videos/dashboard/    (0 seconds)
                          0_FirstTimeLogin.spec.ts.mp4                                              


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  dashboard/1_login.spec.ts                                                      (2 of 11)


  login page for harvester
    ✓ Invalid Login (1376ms)
    ✓ should login successfully (4468ms)
    (Attempt 1 of 2) Log out from valid login
    ✓ Log out from valid login (5465ms)


  3 passing (17s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        3                                                                                │
  │ Passing:      3                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  1                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     17 seconds                                                                       │
  │ Spec Ran:     dashboard/1_login.spec.ts                                                        │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Screenshots)

  -  /home/mike/Projects/tests/cypress/cypress/screenshots/dashboard/1_login.spec.ts/     (1280x720)
     login page for harvester -- Log out from valid login (failed).png                              


  (Video)

  -  Started processing:  Compressing to 32 CRF                                                     
  -  Finished processing: /home/mike/Projects/tests/cypress/cypress/videos/dashboard/     (1 second)
                          1_login.spec.ts.mp4     
```
No failures for the `0_FirstTimeLogin.spec.ts` and the `1_login.spec.ts`.
That side-effect of firstTimeLogin is interesting but it looks like just calling the helper function of validateLogin works well to I guess check the page heading and that it's saying dashboard.  That's a great catch :+1: !
This all looks good :smile:  - I validated against the most recent commit `7d0b45708bf76de59aa31a56d84567fc0f703bf2` as noted that some of the commit is displayed via PS1 in that terminal code-block above.

**Review by irishgordo — APPROVED** [review]
After testing locally this looks good!  Great catch on fixing the race condition that @TachunLin  had mentioned earlier!

**Review by TachunLin — APPROVED** [review]
The test suite can proceed from first time login to the login page and proceed the remaining test cases. 
image

**Pull request merged**
